title: My tittle
author: Me
email: my_email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome description

# social links
twitter_username: your-twitter-handle(my twitter)
github_username:  your-github-handle(my github)

show_excerpts: true # set to false to remove excerpts on the homepage

theme:minima
