title: Tittle
author: author
email: email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 ssssssssssss
baseurl:url
# social links
twitter_username: my twitter
github_username:  my github

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
